### PR TITLE
Loadcell

### PR DESCRIPTION
**Pull request by patou01**
New firmware and readme updated with the load cell

### CODE REVIEW

**Comment by PlantagoLabs** [comment]
Hi, 

Isn't this push better on the Robopoly fork of Roberto ? Or is this to update this fork to the level of the Robopoly's branch ?

**Comment by patou01** [comment]
It was meant for the one of Robopoly. Github decided otherwise, it sent the pull request to this repo instead of ours. Couldn't find where it was hidden to cancel it.

**Comment by PlantagoLabs** [comment]
No problem, I think I will leave this repo as is, as the Robopoly is the real repo. You want me to delete this branch or we just leave it like this ?

Anyway, thanks for still working on Roberto ! It means a lot for me.

**Comment by patou01** [comment]
Yes I'll do the cleaning up (been working on forking the various projects that I have worked on so that I can keep a trace of the state of things when I left). I notice I left another branch open on Roberto for a few years.

It's fun to see that the main repo we forked Roberto off is actually almost empty.

**Comment by PlantagoLabs** [comment]
Sorry wrong button....

Yes, I didn't bother commit stuff years ago and I was strongly invited to commit those three files.... I didn't quite understood the reason for git at the time. 

Now that I stumbled on some source files and made a blog, I commited it all to what I now believe is the main fork at Robopoly. Makes more sense to have everything at one place.

EDIT: typo

**Pull request closed without merging**
